import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const mainSource = () => readFileSync(resolve(process.cwd(), 'src/main.ts'), 'utf8')
const debriefSource = () => readFileSync(resolve(process.cwd(), 'src/ui/debrief.ts'), 'utf8')
const debriefReportSource = () => readFileSync(resolve(process.cwd(), 'src/debrief-report.ts'), 'utf8')
const finishRunSource = () => readFileSync(resolve(process.cwd(), 'src/run/finish-run.ts'), 'utf8')
const optionalSource = (path: string) => {
  try {
    return readFileSync(resolve(process.cwd(), path), 'utf8')
  } catch {
    return ''
  }
}
const stationDockSource = () => optionalSource('src/ui/station-dock.ts')
const stationDockReportSource = () => optionalSource('src/station-dock-report.ts')
const sectorMapScreenSource = () => optionalSource('src/ui/sector-map-screen.ts')
const cssSource = () => optionalSource('src/style.css')

test('sector map is a first class screen between mothership and expeditions', () => {
  const main = mainSource()
  const gameStates = optionalSource('src/game-states.ts')
  const sectorMapScreen = sectorMapScreenSource()

  expect(gameStates).toContain("| 'sectorMap'")
  expect(gameStates).toContain("| 'station'")
  expect(main).toContain('sectorMap: document.createElement')
  expect(main).toContain('station: document.createElement')
  expect(main).toContain("import { showSectorMap as uiShowSectorMap } from './ui/sector-map-screen'")
  expect(main).toContain('private showSectorMap(')
  expect(main).toContain('uiShowSectorMap(this, message)')
  expect(main).toContain('private showStationDock(')
  expect(main).toContain('private launchSectorNode(')
  expect(main).toContain('private completeSectorNodeViaBeacon(')
  expect(main).not.toContain('private sectorNodeGlyph(')
  expect(main).not.toContain('private sectorKindLabel(')
  expect(sectorMapScreen).toContain('export function sectorNodeGlyph(')
  expect(sectorMapScreen).toContain('function sectorKindLabel(')
})

test('sector map choices expose wave and hazard readouts before launch', () => {
  const main = mainSource()
  const sectorMapScreen = sectorMapScreenSource()
  const css = cssSource()

  expect(main).not.toContain("panel.className = 'sector-map-panel'")
  expect(main).not.toContain('private sectorNodePosition(')
  expect(main).not.toContain('private sectorNodeClass(')
  expect(main).not.toContain('private sectorNodeConfigSummary(')
  expect(main).not.toContain('private sectorMapDebugReadout(')
  expect(main).not.toContain('private sectorHazardsLabel(')
  expect(sectorMapScreen).toContain('interface SectorMapView')
  expect(sectorMapScreen).toContain('export function showSectorMap(self: SectorMapView, message: string)')
  expect(sectorMapScreen).not.toContain("from '../main'")
  expect(sectorMapScreen).toContain("panel.className = 'sector-map-panel'")
  expect(sectorMapScreen).toContain('sector-map-hexchart')
  expect(sectorMapScreen).toContain('LOCAL HEX GRID')
  expect(sectorMapScreen).not.toContain('sector-route-string')
  expect(sectorMapScreen).toContain('sector-wire-hex')
  expect(sectorMapScreen).toContain('function sectorWireHexPoints(')
  expect(sectorMapScreen).toContain('body.append(currentPanel, graph, details)')
  expect(sectorMapScreen).not.toContain('sector-station-edges')
  expect(sectorMapScreen).not.toContain('sector-node-glyph">${sectorNodeGlyph(node.kind)}')
  expect(css).toContain('radial-gradient(circle at 12% 18%, rgba(246, 255, 254, 0.28) 0 0.9px, transparent 1.6px)')
  expect(sectorMapScreen).not.toContain('sectorStationEdgeMarkers(')
  expect(sectorMapScreen).toContain('sector-selection-readout')
  expect(sectorMapScreen).toContain('sector-launch-button')
  expect(sectorMapScreen).toContain('let selectedNodeId')
  expect(sectorMapScreen).toContain('function selectSectorChoice(nodeId: string)')
  expect(sectorMapScreen).toContain('sector-choice-metrics')
  expect(sectorMapScreen).toContain('sector-choice-intel')
  expect(sectorMapScreen).toContain('sectorNodeDecisionIntel(node)')
  expect(sectorMapScreen).toContain('node.config.readout')
  expect(sectorMapScreen).toContain('function sectorNodePosition(')
  expect(sectorMapScreen).toContain('node.q')
  expect(sectorMapScreen).toContain('node.r')
  expect(sectorMapScreen).toContain('function sectorNodeClass(')
  expect(sectorMapScreen).toContain('function sectorNodeConfigSummary(')
  expect(sectorMapScreen).toContain('function sectorMapDebugReadout(')
  expect(sectorMapScreen).toContain('ROUTE DEBUG')
  expect(sectorMapScreen).toContain("const wrap = document.createElement('details')")
  expect(sectorMapScreen).toContain("wrap.innerHTML = `<summary>ROUTE DEBUG</summary>")
  expect(sectorMapScreen).not.toContain('sector-node-label')
  expect(sectorMapScreen).toContain('sector-node-frontier')
  expect(sectorMapScreen).toContain("button.classList.toggle('selected', isSelected)")
  expect(sectorMapScreen).toContain("hex.classList.toggle('selected'")
  expect(sectorMapScreen).toContain('node.config.templateId')
  expect(sectorMapScreen).toContain('profile.rewardMultiplier')
  expect(sectorMapScreen).toContain('intel.directive')
  expect(sectorMapScreen).toContain('intel.reward')
  expect(sectorMapScreen).toContain('intel.risk')
  expect(sectorMapScreen).toContain('PLANETS ${sectorPlanetLabel')
  expect(sectorMapScreen).toContain('WAVES ${node.config.waves.length} ${sectorWaveLabel(node.config.waveOrder)}')
  expect(sectorMapScreen).toContain('${sectorFirstWaveLabel(node)}</b><em>CONTACT</em>')
  expect(sectorMapScreen).toContain('FIRST ${sectorFirstWaveLabel(node)}')
  expect(sectorMapScreen).toContain('HAZARDS ${sectorHazardsLabel(node.config.hazards)}')
  expect(sectorMapScreen).toContain('function sectorFirstWaveLabel(')
  expect(sectorMapScreen).toContain('function sectorHazardsLabel(')
  expect(sectorMapScreen).toContain("button.addEventListener('click', () => selectSectorChoice(node.id))")
  expect(sectorMapScreen).toContain("runtime.launchSectorNode(selectedNodeId)")
  expect(main).toContain('private updateSectorWaves(')
  expect(main).toContain('encounterBias: this.sectorNodeProfile.encounterBias')
  expect(main).toContain('private nextSectorSpaceEncounterTime(')
})

test('station docking advances the sector map instead of always ending the run', () => {
  const main = mainSource()

  expect(main).toContain('this.completeSectorNodeViaBeacon()')
  expect(main).toContain("node.kind === 'final'")
  expect(main).toContain("this.finishRun('cleanExtraction')")
  expect(main).toContain('this.showStationDock(this.routeStationDockReport(node))')
  expect(main).toContain('Departure lane open. Choose the next jump.')
})

test('route node completion state mutation is centralized', () => {
  const main = mainSource()

  expect(main).toContain('private completeCurrentSectorNode()')
  expect(main).toContain('this.completeCurrentSectorNode()')
  expect((main.match(/this\.sectorMap = completeSectorNode\(this\.sectorMap\)/g) ?? []).length).toBe(1)
})

test('route profile refresh is centralized after route selection and reset', () => {
  const main = mainSource()

  expect(main).toContain('private setSectorNodeProfile(node: SectorNode)')
  expect(main).toContain('this.setSectorNodeProfile(selected)')
  expect(main).toContain('this.setSectorNodeProfile(this.activeSectorNode())')
  expect((main.match(/this\.sectorNodeProfile = sectorNodeRunProfile\(/g) ?? []).length).toBe(1)
})

test('active route node lookup is centralized behind the game route state', () => {
  const main = mainSource()

  expect(main).toContain('private activeSectorNode(): SectorNode')
  expect(main).toContain('return currentSectorNode(this.sectorMap)')
  expect(main).toContain('sectorNodeRunProfile(this.activeSectorNode())')
  expect(main).toContain('const selected = this.activeSectorNode()')
  expect((main.match(/currentSectorNode\(this\.sectorMap\)/g) ?? []).length).toBe(1)
})

test('route launch toast uses authored node objective copy', () => {
  const main = mainSource()

  expect(main).toContain('node.config.objective')
  expect(main).not.toContain('DOCK AT STATION TO CLEAR ROUTE')
})

test('route launch refreshes hud after selecting the sector node', () => {
  const main = mainSource()
  const launchStart = main.indexOf('private launchSectorNode(')
  const launchEnd = main.indexOf('private enterSectorRoute(', launchStart)
  const launchMethod = main.slice(launchStart, launchEnd)
  const enterStart = main.indexOf('private enterSectorRoute(')
  const enterEnd = main.indexOf('private recordStationVisit(', enterStart)
  const enterMethod = main.slice(enterStart, enterEnd)

  expect(launchMethod).toContain('this.sectorMap = selectSectorNode(this.sectorMap, nodeId)')
  expect(launchMethod).toContain('this.enterSectorRoute(selected)')
  expect(launchMethod).not.toContain("this.state = 'playing'")
  expect(enterMethod).toContain("this.state = 'playing'")
  expect(enterMethod.indexOf('this.updateHud()')).toBeGreaterThan(enterMethod.indexOf('this.showOnly(null)'))
  expect(enterMethod).toContain('this.toast(`${node.label}: ${node.config.objective}`)')
})

test('station docking opens a master command menu with collapsible sections and route map', () => {
  const main = mainSource()
  const stationDock = stationDockSource()
  const stationDockReport = stationDockReportSource()
  const css = readFileSync(resolve(process.cwd(), 'src/style.css'), 'utf8')

  expect(main).toContain("import { buildRouteStationDockReport, buildServiceStationDockReport, type StationDockReport } from './station-dock-report'")
  expect(main).toContain("import { showStationDock as uiShowStationDock } from './ui/station-dock'")
  expect(main).toContain('private showStationDock(report: StationDockReport) {')
  expect(main).toContain('uiShowStationDock(this, report)')
  expect(main).not.toContain("panel.className = 'station-command-panel'")
  expect(main).not.toContain('private stationCommandSection(')
  expect(main).not.toContain('private stationRouteMap(')
  expect(stationDock).toContain('interface StationDockView')
  expect(stationDock).toContain('export function showStationDock(self: StationDockView, report: StationDockReport)')
  expect(stationDock).not.toContain("from '../main'")
  expect(stationDock).toContain("panel.className = 'station-command-panel'")
  expect(stationDock).toContain('function stationCommandSection(')
  expect(stationDock).toContain('function stationRouteMap(')
  expect(stationDock).toContain("workbench.addEventListener('click', () => runtime.openStationWorkbench())")
  expect(stationDock).toContain("route.addEventListener('click', () => runtime.leaveStationForSectorMap())")
  expect(stationDock).toContain('station-command-section')
  expect(stationDock).toContain("import type { StationDockReport } from '../station-dock-report'")
  expect(main).not.toContain('private stationNameForNode(')
  expect(main).not.toContain('private stationFictionForNode(')
  expect(stationDockReport).toContain('export function stationFictionForNode(')
  expect(stationDockReport).toContain('export function buildRouteStationDockReport(')
  expect(stationDockReport).toContain('export function buildServiceStationDockReport(')
  expect(stationDock).toContain('Open Workbench')
  expect(stationDock).toContain('CARGO MANIFEST')
  expect(stationDock).toContain('ROUTE MAP')
  expect(main).toContain('private openStationWorkbench(')
  expect(main).toContain('private leaveStationForSectorMap(')
  expect(css).toContain('.station-command-panel')
  expect(css).toContain('.station-command-section')
})

test('route metric grid adapts to first contact timing without forcing desktop wrap', () => {
  const css = readFileSync(resolve(process.cwd(), 'src/style.css'), 'utf8')

  expect(css).toContain('grid-template-columns: repeat(auto-fit, minmax(64px, 1fr))')
})

test('sector stations offer run services but not permanent meta upgrades', () => {
  const main = mainSource()
  const methodStart = main.indexOf('private applySectorStationServices(')
  const methodEnd = main.indexOf('private prepareSectorNode(', methodStart)
  const stationMethod = main.slice(methodStart, methodEnd)

  expect(main).toContain('private applySectorStationServices(')
  expect(main).toContain('Station services are run-only')
  expect(stationMethod).toContain('buildServiceStationDockReport({')
  expect(stationMethod).not.toContain('purchaseMothershipTier')
})

test('first sector node has shorter station timing to introduce the route loop', () => {
  const main = mainSource()

  expect(main).toContain('private isIntroSectorNode(')
  expect(main).toContain('runBalance.timers.introSectorBeaconSeconds')
  expect(main).toContain('returnBeaconReadyForRoute({')
  expect(main).toContain('introNode: this.isIntroSectorNode(node)')
})

test('dock action stays visible and pulses while a station is available', () => {
  const main = mainSource()
  const css = readFileSync(resolve(process.cwd(), 'src/style.css'), 'utf8')

  expect(main).toContain('const stationAvailable = Boolean(this.returnBeacon)')
  expect(main).toContain('returnBeaconAvailable: stationAvailable')
  expect(main).toContain("from './navigation-planet-lock'")
  expect(main).toContain('canLockPlanetCourse({')
  expect(main).toContain('pendingUpgrades: this.pendingUpgrades')
  expect(main).toContain("this.ui.touchAction.classList.toggle('urgent', stationAvailable)")
  expect(css).toContain('.touch-button.urgent')
  expect(css).toContain('@keyframes dock-action-pulse')
})

test('station visits persist as route memory and journey debrief context', () => {
  const main = mainSource()
  const debriefReport = debriefReportSource()
  const finishRun = finishRunSource()
  const stationDock = stationDockSource()
  const sectorMapScreen = sectorMapScreenSource()
  const planetGeneration = readFileSync('src/planet-generation.ts', 'utf8')

  expect(main).toContain("from './station-memory'")
  expect(main).toContain("from './planet-generation'")
  expect(planetGeneration).toContain("from './planet-names'")
  expect(main).toContain('private stationVisits: StationVisitRecord[] = []')
  expect(main).toContain('private recordStationVisit(')
  expect(stationDock).toContain('station-contact-panel')
  expect(sectorMapScreen).toContain("stateLabel = stationVisit ? 'DOCKED'")
  expect(finishRun).toContain('buildDebriefReport({')
  expect(main).toContain('stationVisits: this.stationVisits')
  expect(finishRun).toContain('stationVisits: input.stationVisits')
  expect(debriefReport).toContain('stationVisits: [...input.stationVisits]')
  expect(debriefReport).toContain('journeyDistanceLy({')
  expect(debriefSource()).toContain('Light Years')
  expect(planetGeneration).toContain('planetNameFor({')
})
